### ISSUE TITLE
IssuerNotFound with ClusterIssuer and nginx on GKE

### ISSUE THREAD

**Issue by Humbertda** [jetstack/google-cas-issuer#43]
I am having an issue configuring google-cas-issuer in GKE.

Here is the script I used to configure cert-manager and google-cas-issuer:

``` bash
kubectl create namespace cert-manager
helm repo add jetstack https://charts.jetstack.io
helm repo update
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --create-namespace \
  --version v1.4.0 \
  --set installCRDs=true

kubectl apply -f https://github.com/jetstack/google-cas-issuer/releases/download/v0.5.2/google-cas-issuer-v0.5.2.yaml
```

(I have also configured workload identity)

And here is the yaml configuration for kubernates:

``` yml
apiVersion: cas-issuer.jetstack.io/v1beta1
kind: GoogleCASClusterIssuer
metadata:
  name: cert-app-issuercluster
spec:
  project: (my project id here)
  location: europe-west1
  caPoolId: www-my-app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-my-app
spec:
  secretName: my-app-tls
  duration: 24h
  renewBefore: 8h
  commonName: my.app
  dnsNames:
    - my.app
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: cert-app-issuercluster
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-all
  annotations:
    cert-manager.io/cluster-issuer: cert-app-issuercluster
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: my.app
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: angular-app
            port: 
              number: 80
  tls:
  - hosts:
    - my.app
    secretName: my-app-tls
```

certificate request description: 

> Normal  IssuerNotFound   19s (x5 over 19s)  cert-manager  Referenced "ClusterIssuer" not found: clusterissuer.cert-manager.io "cert-app-issuercluster" not found

kubectl get googlecasclusterissuers  output:
                  

> NAME                          READY   REASON        MESSAGE
> cert-app-issuercluster   True    CASClientOK   Successfully constructed CAS client

Is there an issue from my configuration ? _(I have replaced host names to my.app)_

**Comment by Humbertda** [comment]
One important line was missing in my Ingress configuration:

`cert-manager.io/issuer-kind: GoogleCASClusterIssuer`

From [cert-manager documentation (https://cert-manager.io/docs/usage/ingress/)](https://cert-manager.io/docs/usage/ingress/):

> cert-manager.io/issuer-kind: the name of an external Issuer controller’s CustomResourceDefinition (only necessary for out-of-tree Issuers)

So the full Ingress configuration would look like this: 

``` yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-all
  annotations:
    cert-manager.io/cluster-issuer: cert-app-issuercluster
    cert-manager.io/issuer-kind: GoogleCASClusterIssuer
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: my.app
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service: 
            name: angular-app
            port: 
              number: 80
  tls:
  - hosts:
    - my.app
    secretName: my-app-tls
```

Suggestion: Add usage examples, or links to common cert-manager use-case. It would help newcomers.
