### ISSUE TITLE
GoogleCASIssuer - Intermediate CA for my app

### ISSUE THREAD

**Issue by sebfere** [jetstack/google-cas-issuer#64]
Hey folks!

Some applications deployed in Kubernetes unfortunately require an CA, i.e. an Intermediate CA, in comparison to End-Entity TLS certs.

Here is a sample `Certificate` for my app.

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-app-pki-certificate
  namespace: my-app
spec:
  commonName: my-app-pki-intermediate-ca
  isCA: true
  privateKey:
    algorithm: EDCSA
    size: 256
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: my-googlecasissuer
  duration: "2160h" # 90d
  renewBefore: "360h" # 15d
  secretName: my-app-pki-certificate
  subject:
    countries:
    - CH
    organizationalUnits:
    - MyApp Intermediate Certification Authority
    organizations:
    - SoKube SA
  usages:
  - cert sign
  - crl sign
```

The generated **CertificateRequest** resource still contains the field `isCA: true` but the actual CSR is missing the `X509 Request Extensions`

```shell
kubectl -n my-app get CertificateRequest my-app-pki-certificate-5x4gb -o yaml | yq e '.spec.request' | base64 -d | openssl req -noout -text
```

```text
        Requested Extensions:
            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
```

The same approach using the Google Cloud CAS service would have generated something like this, which would be the **expected behavior**

```text
        Requested Extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:1
```

With such a CSR, the CertificateRequest remains obviously in a non-ready status, with the following error

```text
casClient.CreateCertificate failed: rpc error: code = InvalidArgument desc = untrustedSignAndLint failed: generic::invalid_argument: lint failed for certificate: invalid certificate: [RFC 5280: 4.2.1.3 & 4.2.1.9]: if the keyCertSign bit is asserted, then the cA bit in the basic constraints extension MUST also be asserted
```

On the Google CAS side, the CA is properly configured and is able to generate working Intermediate CAs.

Here it comes to a simple question - Does the current google-cas-issuer implementation support the creation of Intermediate CAs ?

Thanks for your answer
Cheers!

Note: I've been iterating a lot on the `usages:` adding the `server auth` extended usage, or remove all of them, but I don't think this is the real problem here.
